import Header from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';

const font = Poppins({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900', '200', '600'] });

export const metadata: Metadata = {
	title: 'Anang Firmansyah',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${font.className} h-screen  bg-background`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
				>
					<Header />
					<main className='h-[calc(100%_-_80px)] container'>{children}</main>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
